<a href="https://colab.research.google.com/github/nafiz512/Data-Mining/blob/main/Learn_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


Creating numpy array

In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]


Dimensions in array 1D,2D,3D...

In [4]:
a=np.array(42) #0D array
b=np.array([1,2,3,4,5]) #1D array
c=np.array([[1,2,3],[4,5,6]]) #2D array
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) #3D array

print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


Higher dimensional array

In [5]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)
print("shape of arr: ",arr.shape)

[[[[[1 2 3 4]]]]]
5
shape of arr:  (1, 1, 1, 1, 4)


Access array element

In [6]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1]+arr[4])

1
7


In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])
print(arr[0,2]+arr[1,2])

2
9


Negative indexing

In [8]:
print("value of row 0 and column 3 : ",end='')
print(arr[0][-2])

value of row 0 and column 3 : 2


Slicing arrays    arr[start:end:steps]

In [9]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[0:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[1 2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


Slicing 2D array

In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("actual array")
print(arr)
print("2nd row col 2 to 4")
print(arr[1,1:4])
print("1st row to 2 row with only col 3")
print(arr[0:2,2])
print("1st row to 2 row with col 1 to 3")
print(arr[0:2,1:4])


actual array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd row col 2 to 4
[7 8 9]
1st row to 2 row with only col 3
[3 8]
1st row to 2 row with col 1 to 3
[[2 3 4]
 [7 8 9]]


Checking the data type of an array

In [11]:
arr=np.array([1,2,3,4])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


Converting data type of numpy array

In [12]:
arr=np.array([1.3,2.1,3.5])
newarr=arr.astype('i')# 'i' for integer
print(newarr)
print(newarr.dtype)
#converting to int64
newarr=np.array(newarr,dtype='i8')
print(newarr.dtype)

[1 2 3]
int32
int64


Shape of array

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


NumPy array reshaping

In [14]:
arr=np.array([i for i in range(12)])
newarr=np.reshape(arr,(3,4))
print(newarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


Resahpe Multi-dimension to 1D

In [16]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
newarr=arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


numpy.arange() in Python
The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)

In [17]:
print(np.arange(4).reshape(2,2),'\n')
print(np.arange(4,10),'\n')
print(np.arange(4,20,2))

[[0 1]
 [2 3]] 

[4 5 6 7 8 9] 

[ 4  6  8 10 12 14 16 18]


In [18]:
# aranging numbers from 1 to 2 in steps 0.1
print(np.arange(1,2,0.1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


Numpy array iterating

In [24]:
arr=np.array([[i for i in range(3)],[i for i in range (3,6)]])
for x in arr:
    print(x)
print('another way:')
for x in arr:
    for y in x:
        print(y,end=' ')
    print('')

[0 1 2]
[3 4 5]
another way:
0 1 2 
3 4 5 


Numpy array copy vs view

In [34]:
arr=np.array([i for i in range(10)])
x=arr.copy()
y=arr.view()

arr[0]=100

print(arr)

print('copy of arr')
print(x)

print('view of arr')
print(y)

[100   1   2   3   4   5   6   7   8   9]
copy of arr
[0 1 2 3 4 5 6 7 8 9]
view of arr
[100   1   2   3   4   5   6   7   8   9]


In [33]:
#Every NumPy array has the attribute base that returns None if the array owns the data.
#Otherwise, the base  attribute refers to the original object.
print(x.base)
print(y.base)

None
[100   1   2   3   4   5   6   7   8   9]


Joining NumPy Array
1D array

In [35]:
arr1=np.array([i for i in range(10,20)])
arr2=np.array([i for i in range (20,30)])

arr=np.concatenate((arr1,arr2))
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


join 2D array along with the column(axis=0)

In [36]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


join 2D array along with the row (axis=1)

In [37]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


Joining Arrays Using Stack Functions

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#NumPy provides a helper function: hstack() to stack along rows.
arr = np.hstack((arr1, arr2))
print('using hstack() along rows')
print(arr)
#NumPy provides a helper function: vstack()  to stack along columns.
arr = np.vstack((arr1, arr2))
print('using vstack() along colmns')
print(arr)
#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr = np.dstack((arr1, arr2))
print('using dstack() along height')
print(arr)

using hstack() along rows
[1 2 3 4 5 6]
using vstack() along colmns
[[1 2 3]
 [4 5 6]]
using dstack() along height
[[[1 4]
  [2 5]
  [3 6]]]


<h1>Splitting NumPy Arrays

In [44]:
arr=np.array([i+1 for i in range(9)])

newarr=np.array_split(arr,4)# devide into 4 arrays
print(newarr)
for x in newarr:
    print(x)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[1 2 3]
[4 5]
[6 7]
[8 9]


<h1>Searching Arrays
<h3>To search an element from an array, use the where() method.
 to find the indices of all occurrences of that number.

In [45]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


<H1> NumPy Sorting Arrays

In [46]:
arr=np.array([8,-1,10,3,80,71])
print(np.sort(arr))

[-1  3  8 10 71 80]


In [47]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


<h1>Filter

In [48]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [49]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
