<a href="https://colab.research.google.com/github/nafiz512/Data-Mining/blob/main/Learn_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


Creating numpy array

In [5]:
arr=np.array([1,2,3,4,5,6,7,8])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' '6' '7' '8' 'k']


Dimensions in array 1D,2D,3D...

In [6]:
a=np.array(42) #0D array
b=np.array([1,2,3,4,5]) #1D array
c=np.array([[1,2,3],[4,5,6]]) #2D array
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) #3D array

print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


Higher dimensional array

In [40]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)
print("shape of arr: ",arr.shape)

[[[[[1 2 3 4]]]]]
5
shape of arr:  (1, 1, 1, 1, 4)


Access array element

In [10]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1]+arr[4])

1
7


In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])
print(arr[0,2]+arr[1,2])

2
9


Negative indexing

In [14]:
print("value of row 0 and column 3 : ",end='')
print(arr[0][-2])

value of row 0 and column 3 : 2


Slicing arrays    arr[start:end:steps]

In [18]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[0:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[1 2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


Slicing 2D array

In [25]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("actual array")
print(arr)
print("2nd row col 2 to 4")
print(arr[1,1:4])
print("1st row to 2 row with only col 3")
print(arr[0:2,2])
print("1st row to 2 row with col 1 to 3")
print(arr[0:2,1:4])


actual array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd row col 2 to 4
[7 8 9]
1st row to 2 row with only col 3
[3 8]
1st row to 2 row with col 1 to 3
[[2 3 4]
 [7 8 9]]


Checking the data type of an array

In [31]:
arr=np.array([1,2,3,4])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


Converting data type of numpy array

In [37]:
arr=np.array([1.3,2.1,3.5])
newarr=arr.astype('i')# 'i' for integer
print(newarr)
print(newarr.dtype)
#converting to int64
newarr=np.array(newarr,dtype='i8')
print(newarr.dtype)

[1 2 3]
int32
int64


Shape of array

In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


NumPy array reshaping

In [46]:
arr=np.array([i for i in range(12)])
newarr=np.reshape(arr,(3,4))
print(newarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


Resahpe Multi-dimension to 1D

In [52]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
newarr=arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


numpy.arange() in Python
The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)

In [58]:
print(np.arange(4).reshape(2,2),'\n')
print(np.arange(4,10),'\n')
print(np.arange(4,10,2))

[[0 1]
 [2 3]] 

[4 5 6 7 8 9] 

[4 6 8]
