<a href="https://colab.research.google.com/github/nafiz512/Data-Mining/blob/main/Learn_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


Creating numpy array

In [5]:
arr=np.array([1,2,3,4,5,6,7,8])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' '6' '7' '8' 'k']


Dimensions in array 1D,2D,3D...

In [6]:
a=np.array(42) #0D array
b=np.array([1,2,3,4,5]) #1D array
c=np.array([[1,2,3],[4,5,6]]) #2D array
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) #3D array

print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


Higher dimensional array

In [9]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


Access array element

In [10]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1]+arr[4])

1
7


In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])
print(arr[0,2]+arr[1,2])

2
9


Negative indexing

In [14]:
print("value of row 0 and column 3 : ",end='')
print(arr[0][-2])

value of row 0 and column 3 : 2


Slicing arrays    arr[start:end:steps]

In [18]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[0:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[1 2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
